### ISSUE TITLE
Отправка почты админу

### ISSUE THREAD

**Issue by egorzot** [bitrix-expert/bbc#8]
Спасибо за полезный инструмент!
В документации не указано, как отключить отправку почты админу при выбрасывании эксепшна, хотя описано, что есть 2 способа. 

> По-умолчанию сообщения об ошибках отправляются всегда, кроме случая, когда исключение выброшено по причине отсутствия данных (статус 404). Отключить отправку уведомлений можно двумя способами:

насколько понял, речь идет про свойство трейта common $exceptionNotifier и константу BX_EXC_NOTIFY. Хотелось бы узнать про нюансы использования каждого и увидеть данные веши в доках.

**Comment by niksamokhvalov** [comment]
Спасибо, документация дополнена: http://bbc.bitrix.expert/docs/v1/#Уведомление-об-ошибках.
